name: barn_owl_bottom_tab
description: A customizable animated bottom tab bar with drag interaction.
version: 0.0.1
homepage: https://github.com/TMC-IT-MOBILE/barn-bottom-tab
repository: https://github.com/TMC-IT-MOBILE/barn-bottom-tab
issue_tracker: https://github.com/TMC-IT-MOBILE/barn-bottom-tab/issues

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
